version: '3.8'
services:
  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../../jenkins-mirror:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    restart: unless-stopped